num_var : 2
order : 7
num_samples_train : 1000
num_samples_test: 1000
max_degree : 3           
max_num_terms : 4        # <-------
min_num_terms : 3        # <-------
max_Gdegree : 5          
max_num_Gterms : 5       
max_size : 4             
with_permutation : true
num_duplicants : 1
density : 1.0